CREATE TABLE serial (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) DEFAULT NULL,
  info VARCHAR(145) DEFAULT NULL,
  urlImage VARCHAR(45) DEFAULT NULL,
  urlPreviewImage VARCHAR(45) DEFAULT NULL,
  season INT DEFAULT NULL,
  seria_number INT DEFAULT NULL,
  date date DEFAULT NULL,
  PRIMARY KEY (id)
);